server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: offerride-service
          uri: lb://offerride-service
          predicates:
            - Path=/offerride/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passenger/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/api/auth/**