spring:
  application:
    name: passenger-service
  zipkin:
    base-url: http://127.0.0.1:9411/
eureka:
  instance:
    hostname: localhost  
    
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus