
  
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  application:
    name: offerride-service
    
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/usttaxi_db?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
server:
  port: 9011



eureka:
  instance:
    hostname: localhost    
  
  
